CREATE TABLE Ta (
	aid INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	a2 INT UNIQUE,
	number INT,
	text VARCHAR(64)
)

CREATE TABLE Tb (
	bid INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	b2 INT,
	number INT,
	text VARCHAR(64)
)

CREATE TABLE Tc (
	cid INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	aid INT FOREIGN KEY REFERENCES Ta(aid) ON DELETE CASCADE ON UPDATE CASCADE,
	bid INT FOREIGN Key REFERENCES Tb(bid) ON DELETE CASCADE ON UPDATE CASCADE,
)



DROP TABLE Ta
DROP TABLE Tb
DROP TABLE Tc


